name: Pylint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies and HUB
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install Hub
      run: |
        pip install -e .
    - name: Analysing the code with pylint
      run: |
        pylint hub --disable=all --enable=missing-docstring --ignore-patterns='test_.*py'
